runtime: java17
entrypoint: java -jar target/DBS-0.0.1-SNAPSHOT.jar

# Environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  DB_USER: "dbsuser"
  DB_PASS: "CloudApp2025"
  GOOGLE_CLOUD_PROJECT: "winter-vim-482820-f7"
  GOOGLE_CLOUD_REGION: "us-central1"
  CLOUD_SQL_INSTANCE: "cloud-test-db"

# Instance configuration
instance_class: F1

# Scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Health checks
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300