runtime: java17

env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  CLOUD_SQL_INSTANCE: "winter-vim-482820-f7:us-central1:cloud-test-db"
  DB_USER: "dbsuser"
  DB_PASS: "CloudApp2025"

beta_settings:
  cloud_sql_instances: "winter-vim-482820-f7:us-central1:cloud-test-db"